### ISSUE TITLE
Lift, Drag and Y Force plots problems

### ISSUE THREAD

**Issue by Joaozinho3** [Xero64/pyvlm#5]
When you run aircraft.py, you get a few errors, where 'LatticeTrim' object has no attribute 'plot_trefftz_lift_force_distribution', that is, you cannot plot the ltrm, lattice trimmed object with the plot function from the module.

**Comment by Xero64** [comment]
Thank you for posting the issue. I manage to run it with no errors on my side, so I would like to ask a few questions?

Did you install using `pip install pyvlm` or from a wheel file? Or alternatively, did you clone this repository from GitHub?

The latest version from GitHub should work as long as you have the various dependencies installed.

As for the **LatticeTrim** class not having a "plot_trefftz_lift_force_distribution" method. It is a sub-class of **LatticeResult** which doe have the "plot_trefftz_lift_force_distribution" method, so that shouldn't be an issue.
